CREATE TABLE CHEESE_SCORES
(
    ID BIGINT PRIMARY KEY,
    COMPANY VARCHAR(128),
    PRODUCT_NAME VARCHAR(128),
    RATING VARCHAR(128),
    CATEGORY VARCHAR(256),
    COUNTRY VARCHAR(128),
    COUNTY VARCHAR(128)
);
LOAD DATA INFILE '/run/init/data/world_cheese_awards_2021.csv' 
INTO TABLE CHEESE_SCORES 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;